name: Doorlock
version: '${project.version}'
main: dev.jones.doorlock.Doorlock
api-version: '1.20'
authors: [ _joones, l1ratch ]
description: Запирайте двери на ключи.
softdepend: [WorldGuard]
commands:
  dldebug:
    description: Команда отладки (предназначена только для разработчиков, может быть включена в классе Doorlock)
    permission: doorlock.debug
    permission-message: §cВам запрещено использовать эту команду!
  doorlock:
    description: Можно использовать для перезагрузки плагина, проверки наличия обновлений или проверки версии плагина
    permission: doorlock.manage
    permission-message: §cВам запрещено использовать эту команду!
    usage: §cИспользуйте /doorlock <version|help|update|reload>
  unlock:
    description: Открывает блок, на который вы смотрите.
    permission: doorlock.unlock
    permission-message: §cВам запрещено использовать эту команду!
    usage: §cИспользуйте /unlock без аргументов

