name: Doorlock
version: '${project.version}'
main: dev.jones.doorlock.Doorlock
api-version: '1.20'
authors: [ l1ratch ]
description: Продвинутая система блокировки дверей и блоков от l1ratch. (Основано на коде _joones)
website: https://github.com/l1ratch/DoorLock
softdepend: [WorldGuard]
commands:
  doorlock:
    description: Основная команда плагина
    permission: doorlock.use
    permission-message: §cВам запрещено использовать эту команду!
    aliases: [dl]
    usage: §cИспользуйте /doorlock help
permissions:
  doorlock.use:
    description: Позволяет использовать базовые команды плагина
    default: true
  doorlock.admin:
    description: Полный доступ ко всем функциям плагина
    default: op
    children:
      doorlock.use: true
      doorlock.unlock: true
  doorlock.unlock:
    description: Позволяет использовать команду разблокировки
    default: op
  doorlock.bypass:
    description: Позволяет игнорировать блокировку дверей и блоков
    default: false


